### ISSUE TITLE
Hello, can you provide the hppo_noshare file in the agent folder? Thanks

### ISSUE THREAD

**Issue by yanwei-666** [xujinming01/TD3AQ#2]
Hello, can you provide the hppo_noshare file in the agent folder? Thanks

**Comment by xujinming01** [comment]
I believe you encountered an error while running the `evaluation_plugin.py` file. I've removed it since the `hppo_noshare` algorithm is not utilized in this project. This file was intended for individual testing purposes. You can use `evaluation.py` or create your own evaluation script instead.

**Comment by yanwei-666** [comment]
> I believe you encountered an error while running the `evaluation_plugin.py` file. I've removed it since the `hppo_noshare` algorithm is not utilized in this project. This file was intended for individual testing purposes. You can use `evaluation.py` or create your own evaluation script instead.

Thank you very much for your reply, I understand.
